### PR TITLE
fix: check if change is deleted

### LINKED ISSUE #50: Crash after squash if focusing on working commit
Steps to reproduce

```sh
cd /tmp && mkdir test && cd test
touch a.txt
jj git init && jj new
lazyjj
# focus on working commit

# in new terminal:
echo a > a.txt && jj squash
# return to lazyjj and press Shift-R
```

Error:

```
Error: Failed getting latest heads

Caused by:
    Error: Revision ".." doesn't exist
```

### PR DESCRIPTION
**Pull request by istudyatuni**
fix #50 

- use arc\<mutex\> for storing command history

### CODE REVIEW

File: src/commander/log.rs [hunk 1]
```diff
@@ -164,6 +164,12 @@ impl Commander {
         )
     }
 
+    #[instrument(level = "trace", skip(self))]
+    pub fn is_head_exists(&mut self, head: &Head) -> bool {
```
Comment (istudyatuni) [inline src/commander/log.rs:168]: this function can be very slow

File: src/commander/log.rs [hunk 2]
```diff
@@ -166,22 +166,24 @@ impl Commander {
...
+                "--template",
+                &format!(r#"{} ++ "\n""#, HEAD_TEMPLATE),
+                "-r",
+                head.change_id.as_str(),
+            ],
+            false,
+            true,
+        );
+        let Ok(latest_heads_res) = latest_heads_res else {
+            return self.get_head_latest(&self.get_current_head()?);
```
Comment (Cretezy) [inline src/commander/log.rs:184]: :+1:

**Review by Cretezy — APPROVED** [review]
Thanks! I had done something like this in a private branch.
